name: 树洞

register:
  captcha:
    content: "欢迎您注册${name}，您的验证码是${code}，请在${expire}分钟内完成注册。"
    expire: 10 #minutes
  salt: "D779A3049CBC61E938E43EFF2AB026CE"

db:
  mysql:
    dsn: "root:root@tcp(127.0.0.1:3306)/account?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    dsn: "redis://<user>:<password>@<host>:<port>/<db>"

token:
  expire: 720 #hours
  secret: "12255C8AA7FAE430EA75181CCF5EE94F"

server:
  gateway: ":8088"
  account: ":8081"

email:
  host: "smtp.gmail.com"
  port: 587
  user: "email"
  pass: "password"
  max: 200